package com.amazon.alexa.location;
/* loaded from: classes9.dex */
public final class Features {
    public static final String[] ALL_FEATURES = {"GEOFENCE_ANDROID", "ALEXA_MOBILE_APP_GENERIC_FEATURE_10", "GEOFENCE_ANDROID_PHASE3", "GEOFENCE_ANDROID_REDUCE_SETTING_METRICS", "GEOFENCE_ANDROID_SIMPLIFY_TRIGGER_AUTH_LOGIC", "GEOFENCE_ANDROID_USE_IDENTITY_API_V2", "GEOFENCE_ANDROID_DROP_TRIGGER_RECEIVER"};
    public static final String GEOFENCE_ANDROID = "GEOFENCE_ANDROID";
    public static final String GEOFENCE_ANDROID_DROP_TRIGGER_RECEIVER = "GEOFENCE_ANDROID_DROP_TRIGGER_RECEIVER";
    public static final String GEOFENCE_ANDROID_REDUCE_SETTING_METRICS = "GEOFENCE_ANDROID_REDUCE_SETTING_METRICS";
    public static final String GEOFENCE_ANDROID_SIMPLIFY_TRIGGER_AUTH_LOGIC = "GEOFENCE_ANDROID_SIMPLIFY_TRIGGER_AUTH_LOGIC";
    public static final String GEOFENCE_ANDROID_USE_IDENTITY_API_V2 = "GEOFENCE_ANDROID_USE_IDENTITY_API_V2";
    public static final String GEOFENCE_PHASE3 = "GEOFENCE_ANDROID_PHASE3";
    public static final String IDENTITY_ACCESS_TOKEN_RETRY = "ALEXA_MOBILE_APP_GENERIC_FEATURE_10";

    private Features() {
    }
}
