package com.amazon.photos.discovery.metrics;

import com.amazon.clouddrive.android.core.interfaces.MetricName;
import kotlin.Metadata;
import org.jetbrains.annotations.NotNull;
/* compiled from: DiscoveryMetrics.kt */
@Metadata(bv = {1, 0, 3}, d1 = {"\u0000\u0018\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u000e\n\u0002\bt\b\u0080\u0001\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u00012\u00020\u0002B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\b\u0010\u0004\u001a\u00020\u0005H\u0016j\u0002\b\u0006j\u0002\b\u0007j\u0002\b\bj\u0002\b\tj\u0002\b\nj\u0002\b\u000bj\u0002\b\fj\u0002\b\rj\u0002\b\u000ej\u0002\b\u000fj\u0002\b\u0010j\u0002\b\u0011j\u0002\b\u0012j\u0002\b\u0013j\u0002\b\u0014j\u0002\b\u0015j\u0002\b\u0016j\u0002\b\u0017j\u0002\b\u0018j\u0002\b\u0019j\u0002\b\u001aj\u0002\b\u001bj\u0002\b\u001cj\u0002\b\u001dj\u0002\b\u001ej\u0002\b\u001fj\u0002\b j\u0002\b!j\u0002\b\"j\u0002\b#j\u0002\b$j\u0002\b%j\u0002\b&j\u0002\b'j\u0002\b(j\u0002\b)j\u0002\b*j\u0002\b+j\u0002\b,j\u0002\b-j\u0002\b.j\u0002\b/j\u0002\b0j\u0002\b1j\u0002\b2j\u0002\b3j\u0002\b4j\u0002\b5j\u0002\b6j\u0002\b7j\u0002\b8j\u0002\b9j\u0002\b:j\u0002\b;j\u0002\b<j\u0002\b=j\u0002\b>j\u0002\b?j\u0002\b@j\u0002\bAj\u0002\bBj\u0002\bCj\u0002\bDj\u0002\bEj\u0002\bFj\u0002\bGj\u0002\bHj\u0002\bIj\u0002\bJj\u0002\bKj\u0002\bLj\u0002\bMj\u0002\bNj\u0002\bOj\u0002\bPj\u0002\bQj\u0002\bRj\u0002\bSj\u0002\bTj\u0002\bUj\u0002\bVj\u0002\bWj\u0002\bXj\u0002\bYj\u0002\bZj\u0002\b[j\u0002\b\\j\u0002\b]j\u0002\b^j\u0002\b_j\u0002\b`j\u0002\baj\u0002\bbj\u0002\bcj\u0002\bdj\u0002\bej\u0002\bfj\u0002\bgj\u0002\bhj\u0002\bij\u0002\bjj\u0002\bkj\u0002\blj\u0002\bmj\u0002\bnj\u0002\boj\u0002\bpj\u0002\bqj\u0002\brj\u0002\bsj\u0002\btj\u0002\buj\u0002\bvj\u0002\bwj\u0002\bx¨\u0006y"}, d2 = {"Lcom/amazon/photos/discovery/metrics/DiscoveryMetrics;", "", "Lcom/amazon/clouddrive/android/core/interfaces/MetricName;", "(Ljava/lang/String;I)V", "getEventName", "", "ScanAddedWorkerStarted", "MediaStoreScanError", "MediaStoreFolderCreationError", "MediaStoreParentFileMissingError", "MediaStoreGetBucketIdError", "MediaStoreGetBucketNameError", "MediaStoreGetBucketPathError", "ScanAddedWorkerDiscoveredItems", "ScanAddedWorkerProcessedItems", "ScanAddedWorkerStopped", "DeletedScanStarted", "DeletedScanStopped", "DeletedScanTotalDeleted", "DeletedScanTotalProcessed", "DeletedScanTransactionFailed", "AddedScanFillBatchTime", "AddedScanBatchGetLocalTime", "AddedScanBatchProcessTime", "ScanAddProcessBatchError", "ScanAddFetchBatchError", "ScanAddFetchFolderError", "ScanAddPersistItemsError", "ScanAddGetLocalByPathsDbError", "ScanAddGetLocalByPathsDbRetried", "DeletedScanFetchOneBatchTime", "DeletedScanCheckDeletedTime", "DeletedScanCheckDeletedError", "DeletedScanDeleteTransactionTime", "DeletedScanGetLocalAfterIdError", "DeletedScanGetLocalAfterIdRetried", "QueryExistedPathFailed", "QueryExistedPathSucceedAfterRetry", "GetCursorItemFailed", "GetCursorItemSucceedWithException", "DedupeWorkerStarted", "DedupeNoStagesProvided", "DedupeStageNotFound", "DedupeRetryError", "DedupeNoRetryError", "DiscoveryAbortError", "DedupeNoNextStage", "DedupeStageItemsModified", "DedupeStageItemsProcessed", "DedupeWorkerEmptyBatch", "DiscoveryItemDoneAcrossReboot", "MddCloudDriveError", "MddQueryBatchSize", "MddMissingUnifiedIdError", "MddResponseNodes", "MddLocalImageResolutionMissing", "MddCloudImageResolutionMissing", "MddLocalVideoResolutionMissing", "MddCloudVideoResolutionMissing", "DigestCalculationError", "DigestCalculationFilePathMissingError", "DigestCalculationFileDoesNotExist", "DigestCalculationIOException", "DigestCalculationIllegalState", "DigestLocalItemsSkipped", "DigestPersistenceFailure", "MismatchedGroupMD5s", "CloudNodeInsertionFailure", "DigestBulkGetNodesFailure", "DigestListNodesFailure", "OphaningCloudOnlyGroup", "BreakupNullMd5Items", "MonitorWorkerStarted", "MonitorConsistentDevice", "MonitorInconsistentDevice", "MonitorMoreItemsInDbEvent", "MonitorMoreItemsInDbCount", "MonitorLocalItemDiscrepancy", "MonitorDiscoveryLocalItems", "MonitorMediaStoreItems", "MonitorDedupeIncomplete", "MonitorDedupeComplete", "MonitorUnifiedWithCloud", "MonitorUnifiedWithoutCloud", "MonitorWorkRetryAfterDiscovery", "MonitorWorkRetryAfterScanned", "MonitorMediaStoreCountInvalid", "MonitorLocalCameraItems", "MonitorMediaStoreCameraItems", "MonitorCameraItemsDiscrepancy", "MonitorCameraDirectoryMissing", "MonitorWorkInfoStatusTagUnset", "MonitorLocalInvalidDateTaken", "MonitorMediaStoreImages", "MonitorMediaStoreVideos", "MonitorLocalItemsMissingMd5", "MonitorLocalVideosZeroDuration", "MonitorLocalItemsInvalidSize", "MonitorMissItemEvent", "MonitorMissItemError", "MonitorMissItemCount", "MonitorNoMissItem", "MonitorDupItemsInDbEvent", "MonitorDupItemsInDbCount", "MonitorNoDupItemsInDb", "DedupeCameraBypassedItems", "DedupeCloudBypassedItems", "WorkerRetryOnError", "InjectFailHappened", "InjectSucceed", "DiscoveryItemCompletion", "ScanAddedWorkerComplete", "ScanAddedBatchComplete", "DeletedScanComplete", "DedupeWorkerComplete", "DigestPhotoMd5Calculation", "DigestVideoMd5Calculation", "DigestCalculation", "DedupeStageCompletion", "MonitorWorkerComplete", "WorkerLifetimeComplete", "AndroidPhotosDiscovery_release"}, k = 1, mv = {1, 1, 16})
/* loaded from: classes13.dex */
public enum DiscoveryMetrics implements MetricName {
    ScanAddedWorkerStarted,
    MediaStoreScanError,
    MediaStoreFolderCreationError,
    MediaStoreParentFileMissingError,
    MediaStoreGetBucketIdError,
    MediaStoreGetBucketNameError,
    MediaStoreGetBucketPathError,
    ScanAddedWorkerDiscoveredItems,
    ScanAddedWorkerProcessedItems,
    ScanAddedWorkerStopped,
    DeletedScanStarted,
    DeletedScanStopped,
    DeletedScanTotalDeleted,
    DeletedScanTotalProcessed,
    DeletedScanTransactionFailed,
    AddedScanFillBatchTime,
    AddedScanBatchGetLocalTime,
    AddedScanBatchProcessTime,
    ScanAddProcessBatchError,
    ScanAddFetchBatchError,
    ScanAddFetchFolderError,
    ScanAddPersistItemsError,
    ScanAddGetLocalByPathsDbError,
    ScanAddGetLocalByPathsDbRetried,
    DeletedScanFetchOneBatchTime,
    DeletedScanCheckDeletedTime,
    DeletedScanCheckDeletedError,
    DeletedScanDeleteTransactionTime,
    DeletedScanGetLocalAfterIdError,
    DeletedScanGetLocalAfterIdRetried,
    QueryExistedPathFailed,
    QueryExistedPathSucceedAfterRetry,
    GetCursorItemFailed,
    GetCursorItemSucceedWithException,
    DedupeWorkerStarted,
    DedupeNoStagesProvided,
    DedupeStageNotFound,
    DedupeRetryError,
    DedupeNoRetryError,
    DiscoveryAbortError,
    DedupeNoNextStage,
    DedupeStageItemsModified,
    DedupeStageItemsProcessed,
    DedupeWorkerEmptyBatch,
    DiscoveryItemDoneAcrossReboot,
    MddCloudDriveError,
    MddQueryBatchSize,
    MddMissingUnifiedIdError,
    MddResponseNodes,
    MddLocalImageResolutionMissing,
    MddCloudImageResolutionMissing,
    MddLocalVideoResolutionMissing,
    MddCloudVideoResolutionMissing,
    DigestCalculationError,
    DigestCalculationFilePathMissingError,
    DigestCalculationFileDoesNotExist,
    DigestCalculationIOException,
    DigestCalculationIllegalState,
    DigestLocalItemsSkipped,
    DigestPersistenceFailure,
    MismatchedGroupMD5s,
    CloudNodeInsertionFailure,
    DigestBulkGetNodesFailure,
    DigestListNodesFailure,
    OphaningCloudOnlyGroup,
    BreakupNullMd5Items,
    MonitorWorkerStarted,
    MonitorConsistentDevice,
    MonitorInconsistentDevice,
    MonitorMoreItemsInDbEvent,
    MonitorMoreItemsInDbCount,
    MonitorLocalItemDiscrepancy,
    MonitorDiscoveryLocalItems,
    MonitorMediaStoreItems,
    MonitorDedupeIncomplete,
    MonitorDedupeComplete,
    MonitorUnifiedWithCloud,
    MonitorUnifiedWithoutCloud,
    MonitorWorkRetryAfterDiscovery,
    MonitorWorkRetryAfterScanned,
    MonitorMediaStoreCountInvalid,
    MonitorLocalCameraItems,
    MonitorMediaStoreCameraItems,
    MonitorCameraItemsDiscrepancy,
    MonitorCameraDirectoryMissing,
    MonitorWorkInfoStatusTagUnset,
    MonitorLocalInvalidDateTaken,
    MonitorMediaStoreImages,
    MonitorMediaStoreVideos,
    MonitorLocalItemsMissingMd5,
    MonitorLocalVideosZeroDuration,
    MonitorLocalItemsInvalidSize,
    MonitorMissItemEvent,
    MonitorMissItemError,
    MonitorMissItemCount,
    MonitorNoMissItem,
    MonitorDupItemsInDbEvent,
    MonitorDupItemsInDbCount,
    MonitorNoDupItemsInDb,
    DedupeCameraBypassedItems,
    DedupeCloudBypassedItems,
    WorkerRetryOnError,
    InjectFailHappened,
    InjectSucceed,
    DiscoveryItemCompletion,
    ScanAddedWorkerComplete,
    ScanAddedBatchComplete,
    DeletedScanComplete,
    DedupeWorkerComplete,
    DigestPhotoMd5Calculation,
    DigestVideoMd5Calculation,
    DigestCalculation,
    DedupeStageCompletion,
    MonitorWorkerComplete,
    WorkerLifetimeComplete;

    @Override // com.amazon.clouddrive.android.core.interfaces.MetricName
    @NotNull
    public String getEventName() {
        return name();
    }
}
